spring:
  application:
    name: shopping-app-api-gateway

  ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        ## CUSTOMER SERVICE
        - id: shopping-app-customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        
          
        ## ITEMS SERVICE
        - id: shopping-app-item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**
         
        ## SALES SERVICE
        - id: shopping-app-sales-order-service
          uri: lb://sales-order-service
          predicates:
            - Path=/orders/**
        ## ORDER LOOKUP SERVICE
        - id: order-lookup-service
          uri: lb://order-lookup-service
          predicates:
            - Path=/orderLookUpService/**
          

server:
  port: 8999


