package com.item.util;

public class ApplicationConstants {

	public static String GET_BY_ITEM_NAME_URL="http://localhost:8999/items/laptop";
	public static String EXPECTED_ITEM="{\r\n"
			+ "    \"id\": 6,\r\n"
			+ "    \"name\": \"laptop\",\r\n"
			+ "    \"description\": \"delll laptop\",\r\n"
			+ "    \"price\": 1000.0\r\n"
			+ "}";
	public static String GET_ALL_ITEMS="http://localhost:8999/items/";
	public static String EXPECTED_ALL_ITEMS="[\r\n"
			+ "    {\r\n"
			+ "        \"id\": 3,\r\n"
			+ "        \"name\": \"mobile\",\r\n"
			+ "        \"description\": \" best smartphone\",\r\n"
			+ "        \"price\": 100.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 6,\r\n"
			+ "        \"name\": \"laptop\",\r\n"
			+ "        \"description\": \"delll laptop\",\r\n"
			+ "        \"price\": 1000.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 68,\r\n"
			+ "        \"name\": \"headphones\",\r\n"
			+ "        \"description\": \"boat headphone is the best\",\r\n"
			+ "        \"price\": 450.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 69,\r\n"
			+ "        \"name\": \"cloths\",\r\n"
			+ "        \"description\": \"pan america t-shirt\",\r\n"
			+ "        \"price\": 1000.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 70,\r\n"
			+ "        \"name\": \"stationary\",\r\n"
			+ "        \"description\": \"pen goldex is the best\",\r\n"
			+ "        \"price\": 1000.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 71,\r\n"
			+ "        \"name\": \"makeup\",\r\n"
			+ "        \"description\": \"Loreyal\",\r\n"
			+ "        \"price\": 1000.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 86,\r\n"
			+ "        \"name\": \"toys\",\r\n"
			+ "        \"description\": \"racing cars\",\r\n"
			+ "        \"price\": 100.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 87,\r\n"
			+ "        \"name\": \"musical keyboard\",\r\n"
			+ "        \"description\": \"this is the most beautiful thing\",\r\n"
			+ "        \"price\": 100.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 117,\r\n"
			+ "        \"name\": \"Mouse keyboard Combo\",\r\n"
			+ "        \"description\": \"Deal of the day\",\r\n"
			+ "        \"price\": 1200.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 130,\r\n"
			+ "        \"name\": \"IPhone 14 pro max\",\r\n"
			+ "        \"description\": \"Best Phone Ever\",\r\n"
			+ "        \"price\": 1250.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 137,\r\n"
			+ "        \"name\": \"Bookss\",\r\n"
			+ "        \"description\": \"Spring Boot\",\r\n"
			+ "        \"price\": 100.0\r\n"
			+ "    },\r\n"
			+ "    {\r\n"
			+ "        \"id\": 154,\r\n"
			+ "        \"name\": \"junit Books\",\r\n"
			+ "        \"description\": \"Do your Bestt\",\r\n"
			+ "        \"price\": 10.0\r\n"
			+ "    }\r\n"
			+ "]";
	public static String ADD_ITEM_URL="http://localhost:8999/items/";
	public static String ADDED_ITEM_EXPEXTED="{\r\n" + 
			
			"    \"name\": \"Testing\",\r\n" + 
			"    \"description\": \"integratation testing\",\r\n" + 
			"    \"price\": 100.0\r\n" + 
			"}";
	
}